version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest

steps:
  - checkout # Paso de extraer el código 
  - run: 
      name: Instalar CMake
      command: sudo apt-get update && sudo apt-get install cmake         