version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout 
      - run: 
          name: Instalar CMake
          command: sudo apt-get update && sudo apt-get install cmake  
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest
   